# Achi 卸载脚本 - 删除所有注册
customfunction remove "ACHI_MAIN_"
customfunction remove "check/LandChunks"
customfunction remove "cloneLand"
customfunction remove "debug"
customfunction remove "feedback"
customfunction remove "form/createPlayerSnapshot"
customfunction remove "form/get/AnchorButtonText"
customfunction remove "form/get/SnapshotName"
customfunction remove "form/navigate"
customfunction remove "form/openMenu"
customfunction remove "form/showError"
customfunction remove "form/validatePlayerSelection"
customfunction remove "get/FreeLandIndex"
customfunction remove "initLand"
customfunction remove "process/Backup"
customfunction remove "process/LandInit"
customfunction remove "queue/Peek"
customfunction remove "queue/Pop"
customfunction remove "queue/Push"
customfunction remove "squareSpiralFill"
customfunction remove "worldData/mapDel"
customfunction remove "worldData/mapExist"
customfunction remove "worldData/mapGet"
customfunction remove "worldData/mapKeyOf"
customfunction remove "worldData/mapSet"
customfunction remove "worldData/ptr_mapDel"
customfunction remove "worldData/ptr_mapGet"
customfunction remove "worldData/ptr_mapSet"
customfunction remove "init/main"
customfunction remove "init/verify"
customform remove ACHI_HOME_CONFIG_DEBUG
customform remove ACHI_HOME_CONFIG_ELEVATE
customform remove ACHI_HOME_CONFIG
customform remove ACHI_HOME_LAND_GET
customform remove ACHI_HOME_LAND_SET
customform remove ACHI_HOME_LAND
customform remove ACHI_HOME_PLAYER_ACTION
customform remove ACHI_HOME_PLAYER_ADMIN
customform remove ACHI_HOME_PLAYER_MESSAGE
customform remove ACHI_HOME_PLAYER
customform remove ACHI_HOME_TP_ANCHOR_SET
customform remove ACHI_HOME_TP_ANCHOR
customform remove ACHI_HOME_TP_FIXED-A
customform remove ACHI_HOME_TP_FIXED-B
customform remove ACHI_HOME_TP
customform remove ACHI_HOME
customform remove ACHI_INFO_AGREEMENT
customform remove ACHI_INFO_AGREEMENT_VIEW
customform remove ACHI_INFO_ERROR
customform remove ACHI_INFO_LAND_DEL
customform remove ACHI_INFO_LAND_SET
customform remove ACHI_INFO_RESTORE
tellraw @a {"rawtext":[{"text":"§e--------------------\n§fACHI §c脚本已卸载\n§7时刻: §f2026-05-27 11:16:21\n§e--------------------"}]}